var body_desktop,is_mobile,touchDevice=navigator.userAgent.match(/(iphone|ipod|ipad|android)/i)!=null,headerH=false;var projects={};$(document).ready(function(){body_desktop=$('#device-1');is_mobile=$('#device-2').length;initHeaderSearch();initLanguageSelect();initLoginWindow();initAccountWindow();mobileMenu();mobileCategoryMenu();mobileHeaderControls();initMobileSearch();filterSlider();shareButtons();initProductSlider();customSelect();customRadio();orderAmount();toolTips();filterLoader();loginTrigger();setTabs();setCategoryHeading();shoppingcartFeatures($('#shoppingcart .features, #checkout .features'));shoppingcartStockError();checkoutCustomSelect();setContactMenuItem();registerForm();loginError();scroll_to_bottom();scroll_to_section();scroll_to_top();setItemDataUrl();setAccordion();checkoutValidation();removeRegistrationText();$('#header').headerShadow();$(document).ajaxComplete(function(){if(!$('body').hasClass('tmpl-product')){customSelect();customRadio();$('input:checkbox').each(function(){$('<label class="check" for="'+$(this).attr('id')+'"></label>').insertAfter($(this));});}});if(typeof out_of_stock!=='undefined'){$.each(out_of_stock,function(index,product_id){$item=$('.js_cart_product_'+product_id);$item.addClass('out_of_stock');$item.find('.name').append('<div class="out_of_stock_msg">'+out_of_stock_msg+'</div>');});$('#stock_limits').show(0);}
if($('.payment-description').length>0){var customer_number=$('.payment-description').data('customer-number');var replaced_customer_number=$('.payment-description').html().replace("[customer-number]",'<b>'+customer_number+'</b>');$('.payment-description').html(replaced_customer_number);}
if($('html')[0].lang=='en-us-ca'){$('.logo a').prop('href','/en-ca/');}
if($('.header-controls-mobile .cart').length&&$('.header-cart .total').length&&$('.header-cart .total').text()!='0'){$('.header-controls-mobile .cart').text($('.header-cart .total').text())
$('.header-controls-mobile .cart').attr('href',$('.header-cart a').attr('href'));}
$('#choiseCountryButton').click(function(e){e.preventDefault();});$('#choiseCountryButton').magnificPopup({type:'ajax',overflowY:'scroll'});$('.subscribers_number, .extension, .area_code, .mobile_number2, .mobile_number3').on('keyup focus',function(){textInput=$(this).val().replace(/[\D+\s+]/,"");$(this).val(textInput);});$('.mobile_number1, .country_code').on('keyup focus',function(){textInput=$(this).val().replace(/[^+0-9]/,"");$(this).val(textInput);});$(".mobile_number2").on('keyup',function(){if($(this).val().length>=5){$(this).val($(this).val().substring(0,5));$('.mobile_number3').focus();}});$('#fw_form_field_10').on('keyup focus',function(){if($('#fw_form_field_12 :selected').val()==1){if($(this).val().length<=4){textInput=$(this).val().replace(/[\D+\s+]/,"");$(this).val(textInput);}
if($(this).val().length>=7){$(this).val($(this).val().substring(0,7));}
text=$(this).val().replace(/^(.{4})/,'$1 ');text=text.replace(/(\s)+/g,"$1");splitted=$(this).val().split(' ');if(splitted[1]){var text=splitted[0]+' '+splitted[1].replace(/[\d+]/,"");}
$(this).val(text);}});if($('.big_slider .royalSlider').length){$('.big_slider .fw_rs_text').each(function(){if($.trim($(this).text())==''){$(this).remove();}})
$('.big_slider .fw_rs_img span').each(function(){if($(this).children('img').length)
$(this).css('background-image','url('+$(this).children('img')[0].src+')');});$('.big_slider .royalSlider .fw_rs_text').each(function(){if($(this).text()=='')$(this).remove();});$('.big_slider .fw_rs_img .video_box').each(function(){var $t=$(this),videoObj=checkVideoService($t.text()),screen_width=getScreenWidth();switch(videoObj.type){case'youtube':if(screen_width>=768){$t.html('<iframe class="video_item" src="https://www.youtube.com/embed/'+videoObj.id+'?disablekb=1&fs=0&rel=0&controls=0&showinfo=0&autoplay=1&loop=1&mute=1&playlist='+videoObj.id+'" allowfullscreen="allowfullscreen"></iframe>');}else{$(this).remove();}
break;case'vimeo':$t.html('<iframe class="video_item" src="https://player.vimeo.com/video/'+videoObj.id+'?background=1" width="500" height="281" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>');break;case'mp4':$t.html('<div class="video_item">'+'<video autoplay="autoplay" loop="loop" muted="muted">'+'<source src="'+videoObj.id+'">'+'</video>'+'</div>');$t.closest('.vbg').append('<div class="controls">'+'<div class="play" style="display:none;"></div>'+'<div class="pause"></div>'+'<div class="replay"></div>'+'</div>'+'<div class="sound">'+'<div class="on" style="display:none;"></div>'+'<div class="off"></div>'+'</div>');$t.vid=$t.find('video');$t.vid.attr('loop','loop');$t.vid.prop('muted',true);$t.vid.get(0).load();$t.vid.get(0).play();$t.closest('.vbg').find('.controls .replay').click(function(){$t.vid.get(0).pause();$t.vid.get(0).currentTime='0';$t.vid.get(0).play();});$t.closest('.vbg').find('.controls .play').click(function(){$(this).hide();$(this).parent().find('.pause').show();$t.vid.get(0).play();});$t.closest('.vbg').find('.controls .pause').click(function(){$(this).hide();$(this).parent().find('.play').show();$t.vid.get(0).pause();});$t.closest('.vbg').find('.sound .on').click(function(){$(this).hide();$(this).parent().find('.off').show();$t.vid.get(0).muted=false;});$t.closest('.vbg').find('.sound .off').click(function(){$(this).hide();$(this).parent().find('.on').show();$t.vid.get(0).muted=true;});setTimeout(function(){$t.vid.get(0).play();if($t.vid.get(0).paused){$t.closest('.vbg').find('.controls .pause').click()}},50);break;default:}
$t.css('min-width',1.7777*$t.height());$t.find('.video_item').height($t.height());$(window).load(function(){$t.css('min-width',1.7777*$t.height());$t.find('.video_item').height($t.height());});$(window).resize(function(){$t.css('min-width',1.7777*$t.height());$t.find('.video_item').height($t.height());});});var royal_slider_21_1=$('.big_slider .royalSlider').royalSlider({addActiveClass:true,transitionType:"fade",slidesOrientation:"horizontal",autoHeight:false,arrowsNav:true,arrowsNavAutoHide:false,fadeinLoadedSlide:false,globalCaption:0,loop:true,loopRewind:false,controlNavigation:"bullets",navigateByClick:false,autoPlay:{enabled:true,delay:10000,pauseOnHover:false,stopAtAction:false},randomizeSlides:false,imageScaleMode:"fit-if-smaller",slidesSpacing:0,wrapElements:true,autoScaleSlider:true,autoScaleSliderHeight:637,autoScaleSliderWidth:1500,});var $slider=$('.big_slider .royalSlider').data('royalSlider');$slider.ev.on('rsBeforeAnimStart',function(event){setTimeout(function(){$slider.currSlide.content.find('.replay').click();$(window).trigger('resize');},500);});$slider.ev.on('rsBeforeMove',function(event,type,userAction){var nextSlideId;switch(type){case'prev':if($slider.slides[$slider.currSlideId-1]){nextSlideId=$slider.slides[$slider.currSlideId-1].id}else{nextSlideId=$slider.slides.length-1}
break;case'next':if($slider.slides[$slider.currSlideId+1]){nextSlideId=$slider.slides[$slider.currSlideId+1].id}else{nextSlideId=0}
break;default:nextSlideId=type;}
var $video=$slider.slides[nextSlideId].content.find('.video_item');if($video.length){$video.attr('src',$video.attr('src'));}});$slider.ev.on('rsAfterSlideChange',function(event){});}
$('div.share_block').each(function(){var $t=$(this);$t.buttons=$t.find('div.share_buttons');$t.find('a.tooltip_light').click(function(e){e.preventDefault();if($t.hasClass('active')){$t.removeClass('active').buttons.stop().fadeOut(200);}else{$t.addClass('active').buttons.stop().fadeIn(200);}});});$('input:checkbox').each(function(){$('<label class="check" for="'+$(this).attr('id')+'"></label>').insertAfter($(this));});$('<span class="date_icon"></span>').insertAfter('input.fw_date');if($('.system_overview').length){new MosaikGrid('system');}
projects=!1;if(typeof FW_BusinessProjects=='function'){projects=new FW_BusinessProjects();}
if($('.project_overview').length){new MosaikGrid('project');}
if($('#intro_content').length){if($.cookie("intro_content")=='hidden'){$('#intro_content').hide();$('#show_intro_content').css('display','inline-block');}
$('#show_intro_content').on('click',function(e){e.preventDefault();$('#intro_content').slideDown();$(this).fadeOut();$.cookie("intro_content","visible",{expires:60,path:'/'});});$('#hide_intro_content').on('click',function(e){e.preventDefault();$('#intro_content').slideUp();$('#show_intro_content').fadeIn().css('display','inline-block');$.cookie("intro_content","hidden",{expires:60,path:'/'});});}
$('div.mosaik').parent().mosaikRendering();$('div.old_tabs').tabPlugin();$('a.link_more').on('click',function(e){e.preventDefault();var textWidth=$(this).parent().siblings('div.intro_text').width();$(this).parent().siblings('div.intro_text').css({'position':'absolute','width':textWidth}).animate({'opacity':0});$(this).parent().siblings('div.full_text').css('display','block').animate({'opacity':1});$(this).parent().remove();});if(!touchDevice)$('.tooltip_light').tooltip({tooltipClass:"ui-tooltip_lite",position:{my:"center top+15",at:"center bottom",using:function(position,feedback){$(this).css(position);$("<div>").addClass("arrow").addClass(feedback.vertical).addClass(feedback.horizontal).appendTo(this);}},open:function(event,ui){$('<div class="bg" />').appendTo(ui.tooltip);}});$("#setFilterButton").magnificPopup({type:'inline'});$('.custom_select').customSelect();$('.custom-select').optionSearch();screenSizeCalc();$(window).resize(function(){screenSizeCalc();});$(window).on('load',function(){screenSizeCalc();$('.big_slider').addClass('loaded');});$('a.link_video').each(function(){if($(this).attr('href')!=''&&$(this).attr('href')!="#"){var imgUrl=getScreen(this.href);$(this).find('img').attr('src',imgUrl);}
$(this).magnificPopup({type:'iframe',iframe:{patterns:{youtube:{src:'//www.youtube.com/embed/%id%?autoplay=1&amp;rel=0'}}}});});$('.toggle_submenu').on('click',function(e){e.preventDefault();$(this).next('.fw_main_wrapper').slideToggle();});$('.submenu .fw_subs > a').append('<div class="show_submenu" />');$('.submenu .show_submenu').on('click',function(e){e.preventDefault();$(this).toggleClass('open');$(this).closest('li.fw_subs').find('.fw_subs_wrapper').slideToggle();});if($('#checkout-reference, #checkout-remarks').length){if(typeof($.cookie('checkout-reference'))!='undefined'){$('#checkout-reference').val($.cookie('checkout-reference'));}
$('#checkout-reference').on('blur',function(){$.cookie('checkout-reference',$(this).val(),{expires:60,path:'/'});});if(typeof($.cookie('checkout-remarks'))!='undefined'){$('#checkout-remarks').val($.cookie('checkout-remarks'));}
$('#checkout-remarks').on('blur',function(){$.cookie('checkout-remarks',$(this).val(),{expires:60,path:'/'});});}else{$.removeCookie('checkout-reference',{path:'/'});$.removeCookie('checkout-remarks',{path:'/'});}
if(!$('.header-login-button').length){$('#product .how-to-order').hide();}
$('.cb_color').cbColor();$('.cb_bg').cbBackground();$('.cb_image_bg').cbBackgroundImage();$('.page-64 .submenu .fw_page_64 .show_submenu').click();setYoutubeVideo();$('.js_video_bg').setVideoBackground();});(function($){$.extend($.rsProto,{_wrapElements:function(){var self=this;if(self.st.wrapElements){self.ev.on('rsAfterInit',function(){for(var i=0,$length=self.slides.length;i<$length;i++){$(self.slides[i].content).find('.fw_rs_text').wrapInner('<div class="text" />');};$(self._k5).wrapInner('<div class="wrapper" />');});}},_slideBackground:function(){var self=this;if(self.st.slideBackground){self.ev.on('rsAfterInit',function(){for(var i=0,$length=self.slides.length;i<$length;i++){$(self.slides[i].content[0].innerHTML).find('span').each(function(){console.debug($(this).children('img')[0])
$(this).css('background-image','url('+$(this).children('img')[0].src+')');});console.debug(self.slides[i].content[0].innerHTML)};});}}});$.rsModules.wrapElements=$.rsProto._wrapElements;$.rsModules.slideBackground=$.rsProto._slideBackground;})(jQuery);jQuery.fn.cbColor=function(){return $(this).each(function(){var $t=$(this);if($t.children('.cb_text_color').text().length){$t.color=$t.children('.cb_text_color').text();$t.css('color',$t.color+';');}});};jQuery.fn.cbBackground=function(){return $(this).each(function(){var $t=$(this);if($t.children('.cb_bg_color').text().length){$t.bg=$t.children('.cb_bg_color').text();$t.css('background-color',$t.bg+';');}});};jQuery.fn.cbBackgroundImage=function(){return $(this).each(function(){var $t=$(this);if($t.children('.cb_bg_image').find('img').length){$t.img=$t.children('.cb_bg_image').find('img');$t.css('background-image','url('+$t.img.attr('src')+')');}});};function getScreenWidth(){return $('#page').width();}
function checkoutValidation(){var $btn=$('#button-order-confirm'),$wrapper=$('#checkout .order'),$input=$('#confirmation');$wrapper.on('click',function(e){if(!$input.prop('checked')){$input.addClass('error');}});$input.on('change',function(e){$(this).removeClass('error');if($input.prop('checked')){$btn.addClass('active');}else{$btn.removeClass('active');}});}
function checkAccountIcon(){var header_login_button=$('#header .header-login-button');var mobile_header_login_button=$('#header .header-controls-mobile .trigger-account');if(header_login_button.length!=1){mobile_header_login_button.hide(0);}}
function scroll_to_bottom(){$('#scroll_to_bottom').on('click',function(e){e.preventDefault();$offset=$('#footer').offset().top;$('html,body').stop().animate({scrollTop:$offset},800)});}
function scroll_to_section(){$('.scroll_to_section').on('click',function(e){e.preventDefault();var section=$(this).attr('href');$offset=$(section).offset().top;$('html,body').stop().animate({scrollTop:$offset},800)});}
function scroll_to_top(){$('.scroll_to_top').on('click',function(e){e.preventDefault();$('html,body').stop().animate({scrollTop:0},800)});$(window).on('scroll',function(){if($(window).scrollTop()>$(window).height()/2){$('.scroll_to_top').addClass('active');}else{$('.scroll_to_top').removeClass('active');}}).scroll();}
function registerForm(){var body=$('body');if(body.hasClass('page-2')){if($("#fw_form_wrapper_10 .fw_form_feedback_success").length>0){window.location='/';}}}
function setAccordion(){var accordions=$('.accordion');accordions.each(function(){var accordion=$(this);var items=accordion.find('.accordion-item');if(items.length){function setHandlerEvent(){items.each(function(){var item=$(this);var handler=item.find('.accordion-handler');handler.on('click touchstart',function(e){e.preventDefault();if(!item.hasClass('open')){items.removeClass('open');item.addClass('open');}
else{item.removeClass('open');}
animateItems();});});}
function setHashItem(){var hash=window.location.hash;var hash_item=hash.replace('#','');if(hash_item.length){target_item=accordion.find('.accordion-item[data-id="'+hash_item+'"]');if(target_item.length){target_item.addClass('open');animateItems();}}}
function animateItems(){var active_item=accordion.find('.accordion-item.open .accordion-content');var nonactive_items=accordion.find('.accordion-item:not(.open) .accordion-content');if(active_item.length){active_item.css('height','auto');var auto_height=active_item.outerHeight();active_item.css('height','0');active_item.stop().animate({height:auto_height},400);}
if(nonactive_items.length){nonactive_items.stop().animate({height:0},400);}}
setHandlerEvent();setHashItem();if("onhashchange"in window){window.addEventListener("hashchange",function(){items.removeClass('open');setHashItem();});}
$(window).resize(function(){var active_item=accordion.find('.accordion-item.open .accordion-content');active_item.css('height','auto');var auto_height=active_item.outerHeight();active_item.css('height',auto_height);});}});}
function setContactMenuItem(){var contacts_node=$('li.fw_page_30').first();if(contacts_node.length>0){$('li.fw_page_16').after(contacts_node);}}
function setMoodboardMenuItem(){var moodboard_node=$('li.fw_page_140').first();if(moodboard_node.length>0){$('li.fw_page_30').after(moodboard_node);}}
function disableFields(){var form_node=$('#change-request');if(form_node.length>0){form_node.find('input[type="text"], select').each(function(){$(this).attr('disabled','disabled');});form_node.find('#fw_form_field_32').each(function(){$(this).removeAttr('disabled');$(this).attr('readonly','readonly');});form_node.find('a.select-button').css('pointer-events','none');$('.change-request').on('click','input',function(){var url=$('.fw_page_33 a').attr('href');window.location=url;});}}
function initHeaderSearch(){var header_search=$('.header-search');if(header_search.length){var button=header_search.find('.button');var form=header_search.find('form');var icon=form.find('.icon');var input=header_search.find('input');button.bind('click',function(e){e.preventDefault();header_search.toggleClass('active');if(!header_search.hasClass('active')){input.blur();}});icon.bind('click',function(){form.submit();});form.on('submit',function(){icon.addClass('loading');})}}
function initLanguageSelect(){var language_select=$('.header-language .select');if(language_select.length){$('html').bind('click',function(){language_select.removeClass('active');});var button=language_select.find('.button');var dropdown=language_select.find('.dropdown');button.bind('click',function(e){e.preventDefault();e.stopPropagation();language_select.toggleClass('active');});dropdown.bind('click',function(e){e.stopPropagation();});}}
function initLoginWindow(){var login_button=$('.header-login-button');var login_window=$('.header-login-window');if(login_button.length,login_window.length){var button=login_button.find('.button');button.bind('click',function(e){e.preventDefault();login_button.toggleClass('active');login_window.toggleClass('active');});}}
function initAccountWindow(){var header_account=$('.header-account');var account_window=$('.header-account .header-account-menu');if(header_account.length,account_window.length){$('html').bind('click',function(){header_account.removeClass('active');});var button=header_account.find('.button');button.bind('click',function(e){e.preventDefault();e.stopPropagation();header_account.toggleClass('active');});account_window.bind('click',function(e){e.stopPropagation();});}}
function mobileMenu(){var trigger=$('.header-mobile-trigger');var page=$('#page');if(trigger.length&&page.length){trigger.bind('click',function(e){e.preventDefault();trigger.add(page).add('.part-mobile-menu').toggleClass('active');$('html, body').toggleClass('menu_open');});}}
function mobileHeaderControls(){var trigger=$('.header-controls-mobile .trigger');var part=$('#mobile-listener .part');if(trigger.length&&part.length){trigger.on('click',function(e){e.preventDefault();if($(this).hasClass('active')){trigger.add(part).removeClass('active');$('html, body').removeClass('menu_open');}else{$('html, body').addClass('menu_open');trigger.add(part).removeClass('active');$(this).add(part.filter('.'+$(this).data('part'))).add(trigger.filter('.trigger-menu')).addClass('active');}});}}
function mobileCategoryMenu(){var category_menu_mobile=$('#category-menu-mobile .menu');if(category_menu_mobile.length){var main_items=category_menu_mobile.find('> ul > li > a');main_items.each(function(){var active_sub=$(this).parent().find('.active');if(active_sub.length){$(this).parent().addClass('sub_active');}});main_items.bind('click',function(e){var submenu=$(this).parent().find('ul');if(!$(this).parent().hasClass('active')&&submenu.length){e.preventDefault();$(this).parent().addClass('active');}});}}
function initMobileSearch(){var mobile_search=$('.mobile-search');if(mobile_search.length){var button=mobile_search.find('.button');var form=mobile_search.find('form');var icon=form.find('.icon');button.bind('click',function(e){e.preventDefault();mobile_search.toggleClass('active');});icon.bind('click',function(){form.submit();});}}
function filterSlider(){var menu_filters=$('#menu-filters');if(menu_filters.length){var buttons=menu_filters.find('.button > a');var left=menu_filters.find('.left');var right=menu_filters.find('.right');buttons.bind('click',function(e){e.preventDefault();if(menu_filters.hasClass('right')){menu_filters.removeClass('right');menu_filters.addClass('left');menu_filters.css('height',left.outerHeight()+1);}
else{menu_filters.removeClass('left');menu_filters.addClass('right');menu_filters.css('height',right.outerHeight()+1);}});$(window).resize(function(){if(menu_filters.hasClass('right')){menu_filters.css('height',right.outerHeight()+1);}
else{menu_filters.css('height',left.outerHeight()+1);}});}
var category_menu=$('#category-menu .menu');if(category_menu.length){var main_items=category_menu.find('> ul > li > a');main_items.each(function(){var active_sub=$(this).parent().find('.active');if(active_sub.length){$(this).parent().addClass('active');$(window).resize();}});}}
function shareButtons(){var share=$('.share');if(share.length){var button=share.find('.button');button.bind('click',function(e){e.preventDefault();share.toggleClass('active');});}}
function initProductSlider(){var product_slider=$('#product-slider');if(product_slider.length){product_slider.royalSlider({autoScaleSlider:false,imageScaleMode:'fit-if-smaller',autoScaleSliderHeight:337,imageScalePadding:0,arrowsNav:false,slidesSpacing:0,slidesOrientation:'horizontal',transitionType:'slide',controlNavigation:'thumbnails',thumbs:{orientation:'horizontal',autoCenter:false,spacing:8,firstMargin:8,arrowsAutoHide:true,}});}}
function customSelect(){var selects=$('body').find(':not(.custom-select) > select');if(selects.length){selects.wrap('<div class="custom-select">');var wrappers=selects.parent();selects.each(function(){var select=$(this);var options=select.find('option');var selected=select.find('option:checked');var button=$('<a href="#" class="select-button"><span>'+selected.text()+'</span></a>');var wrapper=select.parent();var list=$('<ul>');options.each(function(index){var list_item=$('<li><a href="#" data-value="'+$(this).val()+'">'+$(this).text()+'</a></li>');if($(this).is(':checked')){list_item.addClass('active');}
list.append(list_item);});wrapper.append(button,list);$('html').bind('click touchend',function(e){if($(e.target).closest(wrappers).length)return;wrappers.removeClass('active');});button.bind('click',function(e){e.preventDefault();e.stopPropagation();wrappers.not(wrapper).removeClass('active invert');if(wrapper.closest('.popup-wrapper').length){var popupWrapper=wrapper.closest('.popup-wrapper');if(Math.abs(wrapper.offset().top-popupWrapper.offset().top-popupWrapper.height())<200){wrapper.toggleClass('invert');}}
wrapper.toggleClass('active');});var list_item_anchors=list.children().find('a');list_item_anchors.bind('click',function(e){e.preventDefault();e.stopPropagation();list_item_anchors.each(function(){$(this).parent().removeClass('active');});$(this).parent().addClass('active');button.find('span').text($(this).text());var new_value=$(this).data('value');select.val(new_value);select.change();wrapper.removeClass('active');});});}}
function customRadio(){var radios=$('input[type=radio]');radios.each(function(){var parent=$(this).parent();parent.append('<div class="custom-radio">');});radios.change(function(){radios.each(function(){var parent=$(this).parent();if($(this).is(':checked')){parent.addClass('checked');}
else{parent.removeClass('checked');}});});radios.change();}
function orderAmount(){var order_fields=$('#order-fields');var price_field=$('#price-field');if(price_field.length){var original_price_text=price_field.attr('content');var price_text=(Math.round(original_price*100)/100).toFixed(3);var price_text=original_price_text.replace(',','').replace('.',',');var original_price=parseFloat(price_text.replace('.','').replace(',','.'));}
if(order_fields.length){var order_value=order_fields.find('#order-amount');var order_multiplier=order_fields.find('#order-multiplier');var order_amount=order_fields.find('#order-value');order_amount.attr('readonly',true);var multiplier=parseInt(order_multiplier.val())||1;var amount=parseInt(order_amount.val())||1;order_multiplier.val(multiplier);var value=parseInt(order_value.val())||1;order_amount.val(value*multiplier);if(price_field.length){var new_price=(original_price*parseInt(order_amount.val())).toFixed(2);var new_price_text=new_price.toString();new_price_text=new_price_text.replace('.',',');price_field.text(addDots(new_price_text));}
order_value.bind('keypress',function(e){var value=parseInt(String.fromCharCode(e.which));if(isNaN(value)){var is_numeric=false;}
else{var is_numeric=true;}
return is_numeric;});order_value.bind('keyup',function(){var value=parseInt(order_value.val())||1;var multiplier=parseInt(order_multiplier.val())||1;order_amount.val(value*multiplier);if(price_field.length){var new_price=(original_price*parseInt(order_amount.val())).toFixed(2);var new_price_text=new_price.toString();new_price_text=new_price_text.replace('.',',');price_field.text(addDots(new_price_text));}});order_value.bind('blur',function(){if(!order_value.val().length){order_value.val(1);}
else if(parseInt(order_value.val())<1){order_value.val(1);}
var value=parseInt(order_value.val())||1;var multiplier=parseInt(order_multiplier.val())||1;order_amount.val(value*multiplier);if(price_field.length){var new_price=(original_price*parseInt(order_amount.val())).toFixed(2);var new_price_text=new_price.toString();new_price_text=new_price_text.replace('.',',');price_field.text(addDots(new_price_text));}});}}
function addDots(nStr){nStr+='';x=nStr.split(',');x1=x[0];x2=x.length>1?','+x[1]:'';var rgx=/(\d+)(\d{3})/;while(rgx.test(x1)){x1=x1.replace(rgx,'$1'+'.'+'$2');}
return x1+x2;}
function toolTips(){var elements=body_desktop.find('.allow-tooltips img[alt], .allow-tooltips *[data-tooltip]');elements.each(function(){var element=$(this);var value='';var display_type=(element.css('display')=='inline')?'inline-block':element.css('display');if(typeof $(this).attr('alt')!==typeof undefined&&$(this).attr('alt')!==false){value=$(this).attr('alt');}
else if(typeof $(this).data('tooltip')!==typeof undefined&&$(this).data('tooltip')!==false){value=$(this).data('tooltip');}
element.wrap('<div class="tooltip-wrapper">');var tooltip_wrapper=element.parent();var tooltip=$('<div class="tooltip"><span class="icon"></span><span>'+value+'</span></div>');tooltip_wrapper.css('display',display_type);tooltip_wrapper.append(tooltip);element.hover(function(){var tooltip_wrapper=$(this).parent();if(tooltip_wrapper.hasClass('tooltip-wrapper')){tooltip_wrapper.addClass('open');}},function(){var tooltip_wrapper=$(this).parent();if(tooltip_wrapper.hasClass('tooltip-wrapper')){tooltip_wrapper.removeClass('open');}});});}
function filterLoader(){var filter_blocker=$('#menu-filters .blocker');var filters=$('#menu-filters .filters a');if(filter_blocker.length&&filters.length){filters.click(function(e){var checkbox=$(this).find('.checkbox');var loader=$(this).find('.loader');checkbox.css('display','none');loader.css('display','block');filter_blocker.css('display','block');});}}
function loginTrigger(){var trigger_login=$('.trigger-login');var login_button=$('.header-login-button');var login_window=$('.header-login-window');var page=$('#page');var header_mobile_trigger=$('.header-controls-mobile .trigger-account');if(trigger_login.length&&login_button.length&&login_window.length&&page.length&&!header_mobile_trigger.is(':visible')){trigger_login.bind('click',function(e){e.preventDefault();var duration=($(window).scrollTop()>500)?500:$(window).scrollTop();$('html, body').animate({scrollTop:0},duration);setTimeout(function(){page.addClass('active');login_button.addClass('active');login_window.addClass('active');},duration);});}else{var part_mobile_account=$('.part-mobile-account');var inner=part_mobile_account.find('.inner');var button=inner.find('> a.button');if(button.length>0){var url=button.attr('href');$('.header-controls-mobile > li > a.trigger-account').attr('href',url).attr('target','_blank').unbind('click');}else{if(inner.find('> *').length==0){$('.header-controls-mobile .trigger-account').hide();}
trigger_login.on('click',function(e){e.preventDefault();header_mobile_trigger.trigger('click');})}
if($('.part-mobile-search').length==0){$('.header-controls-mobile .trigger-search').hide();}}}
function setTabs(){var tab_menus=$('.tab-menu');tab_menus.each(function(){var tab_menu=$(this);var triggers=tab_menu.find('.tab');var listeners=tab_menu.find('.content');if(triggers.length&&listeners.length){triggers.first().addClass('active');listeners.first().addClass('active');}
triggers.bind('mousedown touchend',function(){var trigger=$(this);var data_id=trigger.data('id');if(typeof data_id!==typeof undefined&&data_id!==false){var listener=tab_menu.find('#'+data_id);listeners.removeClass('active');listener.addClass('active');triggers.removeClass('active');trigger.addClass('active');}});});}
function setCategoryHeading(){var categories=$('.categories');var category_heading=$('#category-heading');var category_width_subs=$('.category_with_subs');if(categories.length&&category_heading.length&&category_width_subs.length){category_heading.remove();}}
function shoppingcartFeatures(shoppingcart_features){shoppingcart_features.each(function(){var button=$(this).find('.button');var item_wrapper=$(this).find('.items');var init_height=parseInt(item_wrapper.css('height'));item_wrapper.css('height',init_height);button.bind('click',function(e){e.preventDefault();if(!item_wrapper.hasClass('active')){var auto_height=item_wrapper.css('height','auto').outerHeight();item_wrapper.css('height',init_height);item_wrapper.animate({height:auto_height},250,function(){item_wrapper.css('height','auto');item_wrapper.addClass('active');});}
else{item_wrapper.animate({height:init_height},250,function(){item_wrapper.removeClass('active');});}});});}
function shoppingcartStockError(){var $errorSection=$("#shoppingcart .error");var $errorMessage=$("#shoppingcart #stock_errormessage").text();if($errorSection.length){var $errorList=$("#shoppingcart .error > ul > li");var $productList=$("#shoppingcart .cart .tbody .td.name");$errorList.each(function(){var $productName=$(this).text().replace(/\s+/g,'').toLowerCase();$productList.each(function(){var $anchorText=$(this).find("> a").text().replace(/\s+/g,'').toLowerCase();if($anchorText===$productName){$(this).append('<div class="out_of_stock_msg">'+$errorMessage+'</div>');}});});$errorSection.remove();}
var productID=getUrlParameter("product");if(typeof productID!='undefined'){$product=$("#shoppingcart .cart .tbody .tr.js_cart_product_"+productID+" .td.name");if($product.length)$product.append('<div class="out_of_stock_msg">'+$errorMessage+'</div>');console.log(1)
$('#stock_limits').show(0);}}
function getUrlParameter(sParam){var sPageURL=decodeURIComponent(window.location.search.substring(1)),sURLVariables=sPageURL.split('&'),sParameterName,i;for(i=0;i<sURLVariables.length;i++){sParameterName=sURLVariables[i].split('=');if(sParameterName[0]===sParam){return sParameterName[1]===undefined?true:sParameterName[1];}}}
function checkoutCustomSelect(){var $form=$("form#form-deliver-or-pickup");if($form.length){var $elementsToCorrect=$form.find(".custom-select > .select-button > span, .custom-select > ul > li > a");$elementsToCorrect.each(function(){var $text=$(this).text();var $split=$text.split(": ");if($split.length>1){$(this).text($split[$split.length-1]);}});}}
function loginError(){$(document).ajaxComplete(function(event,request,settings){var data=settings.data;if(typeof data!=="undefined"&&typeof data!=="object"){if(data.indexOf('action=login')>-1){var responseText=JSON.parse(request.responseText);$('.login .error').text(responseText.data.message);}}});}
jQuery.fn.mapInitialize=function(){$.fn.extend({setMarkers:function(points){console.log('setMarkers')
var $t=this;var image={url:'/img/bg/map_marker.png',size:new google.maps.Size(29,37),origin:new google.maps.Point(0,0),anchor:new google.maps.Point(15,37)},image_active={url:'/img/bg/map_marker_active.png',size:new google.maps.Size(29,37),origin:new google.maps.Point(0,0),anchor:new google.maps.Point(15,37)};var shape={coord:[14,37,1,21,1,8,11,1,19,1,29,8,29,21,16,37],type:'poly'};for(type in mapPoints){var points=mapPoints[type];$t.markers[type]=[];var tmp=[];for(i in points){tmp.push(points[i]);}
points=tmp;for(var i=0;i<points.length;i++){var point=points[i];var myLatLng=new google.maps.LatLng(point.coords[0],point.coords[1]);var point_image=image,point_image_active=image_active;if(point.main){point_image={url:'/img/bg/map_marker_main.png',size:new google.maps.Size(29,37),origin:new google.maps.Point(0,0),anchor:new google.maps.Point(15,37)};point_image_active={url:'/img/bg/map_marker_main_active.png',size:new google.maps.Size(29,37),origin:new google.maps.Point(0,0),anchor:new google.maps.Point(15,37)};}
var marker=new google.maps.Marker({position:myLatLng,map:null,icon:point_image,shape:shape,title:point.title,zIndex:point.z_index});marker.image=point_image;marker.image_active=point_image_active;$t.markers[type].push(marker);$t.markers[type][i].infowindow=new google.maps.InfoWindow({content:'<div class="map_info"><h4>'+point.title+'</h4>'+point.text+'</div>',maxWidth:600,pixelOffset:{'width':0,'height':11}});google.maps.event.addListener($t.markers[type][i],'click',function(){if(this==$t.lastMarker){$t.lastMarker.setIcon($t.lastMarker.image);$t.lastMarker.infowindow.close();$t.lastMarker=false;return;}
if($t.lastMarker){$t.lastMarker.setIcon($t.lastMarker.image);$t.lastMarker.infowindow.close();}
this.setIcon(this.image_active);this.infowindow.open($t.map,this);$t.lastMarker=this;var $popup_parent=$('div.map_info').parent().parent().parent().siblings().addClass('map_popup');var k=0;$popup_parent.find('div.gm-style-iw').prev().children('div').each(function(){$(this).addClass('div_'+k++);});$popup_parent.find('div.gm-style-iw').next().addClass('close').click(function(){$t.lastMarker.setIcon($t.lastMarker.image);$t.lastMarker.infowindow.close();$t.lastMarker=false;});});}}},showMarkers:function(type){var $t=this;for(tp in mapPoints){for(var i=0;i<$t.markers[tp].length;i++){$t.markers[tp][i].setMap(null);}}
for(var i=0;i<$t.markers[type].length;i++){$t.markers[type][i].setMap($t.map);}},makeAreabuttons:function(){var $t=this;for(area in mapAreas){var $newLink=$('<a class="button pie" href="#'+mapAreas[area].hash+'">'+mapAreas[area].title+'</a>');$newLink.appendTo($t.leftButtons);}
$t.leftButtons=$t.leftButtons.find('a');$t.leftButtons.click(function(e){e.preventDefault();if($(this).hasClass('active_button'))return $(this);$t.leftButtons.removeClass('active_button');$(this).addClass('active_button');$t.map.setZoom(mapAreas[$(this).index()].zoom);$t.map.setCenter(new google.maps.LatLng(mapAreas[$(this).index()].center[0],mapAreas[$(this).index()].center[1]));}).filter(':first').addClass('active_button');}});return $(this).each(function(){var $t=$(this);$t.lastInfoWindow=false;$t.lastMarker=false;$t.markers=[];$t.rightButtons=$t.parent().find('div.right_buttons a');$t.leftButtons=$t.parent().find('div.left_buttons');var tmp=[];for(i in mapAreas){tmp.push(mapAreas[i]);}
mapAreas=tmp;$t.mapOptions={zoom:mapAreas[0].zoom,center:new google.maps.LatLng(mapAreas[0].center[0],mapAreas[0].center[1]),mapTypeId:google.maps.MapTypeId.ROADMAP,disableDefaultUI:true,scrollwheel:false,styles:[{featureType:'water',elementType:'geometry',stylers:[{color:'#c5ccd2'}]},{elementType:'labels.text.fill',stylers:[{color:'#1f2121'}]},{elementType:'labels.text.stroke',stylers:[{color:'#d5dce3'}]},{featureType:'road',elementType:'geometry',stylers:[{color:'#82878b'}]},{featureType:'landscape',elementType:'geometry',stylers:[{hue:'#ced5db'},{gamma:1.1}]},{featureType:'poi',elementType:'geometry',stylers:[{color:'#b9bfc5'}]},{featureType:'administrative.country',elementType:'geometry.stroke',stylers:[{color:'#595c5f'},{weight:1}]}]}
$t.map=new google.maps.Map(document.getElementById('map_container'),$t.mapOptions);$t.makeAreabuttons();$t.setMarkers();$t.rightButtons.click(function(e){e.preventDefault();if($(this).hasClass('active_button'))return $(this);$t.rightButtons.removeClass('active_button');$(this).addClass('active_button');$t.showMarkers($(this).attr('href').slice(1));});$t.rightButtons.filter(':first').click();});};jQuery.fn.mosaikRendering=function(){return $(this).each(function(){var $t=$(this);$t.mosaics=$t.find('div.mosaik');$t.mosaics.filter(':odd').addClass('mosaik_odd');$t.mosaics.each(function(){var count=$(this).find('div.item').length;$(this).addClass('mosaik_count_'+count);if($(this).hasClass('mosaik_odd')){switch(count){case 2:$(this).find('.item').eq(0).addClass('item_vertical');$(this).find('.item').eq(1).addClass('item_vertical');case 3:$(this).find('.item:first').addClass('item_big');$(this).find('.item').eq(1).addClass('item_vertical');$(this).find('.item').eq(2).addClass('item_vertical');break;case 4:$(this).find('.item:first').addClass('item_vertical');$(this).find('.item:last').addClass('item_big');break;case 5:$(this).find('.item:first').addClass('item_vertical');$(this).find('.item').eq(3).addClass('item_horizontal');$(this).find('.item:last').addClass('item_horizontal');break;case 6:$(this).find('.item:first').addClass('item_vertical');$(this).find('.item').eq(3).addClass('item_horizontal');break;default:$(this).find('.item').addClass('item_big');}}else{switch(count){case 3:$(this).find('.item').eq(1).addClass('item_horizontal');$(this).find('.item').eq(2).addClass('item_horizontal');break;case 4:$(this).find('.item').eq(1).addClass('item_horizontal');break;case 5:$(this).find('.item:first').addClass('item_big');break;default:$(this).find('.item').addClass('item_big');}}
$(this).find('.item').each(function(){var src=$(this).find('.image_square').data('src');$(this).find('img').prop('src',src);if($(this).hasClass('item_horizontal')){src=$(this).find('.image_horizontal').data('src');if(src)$(this).find('img').prop('src',src);}
if($(this).hasClass('item_vertical')){src=$(this).find('.image_vertical').data('src');if(src)$(this).find('img').prop('src',src);}});});screenSizeCalc();});};jQuery.fn.tabPlugin=function(){return $(this).each(function(){var $t=$(this);$t.links=$t.find('ul.tabs_titles');$t.tabs=$t.find('div.tab').hide();$t.links.find('a').click(function(e){e.preventDefault();$t.links.find('.active').removeClass('active');$t.tabs.hide();$t.find($(this).addClass('active').attr('href')).show().find('div.responsive_carousel ul').trigger("updateSizes");});$t.links.find('a:first').click();});};jQuery.fn.customSelect=function(){return jQuery(this).each(function(){var $t=jQuery(this),timer;if($t.find('a.current').length)return $t;$t.ul=$t.find('ul');if(!$t.ul.find('li.fw_active').length)$t.ul.find('li:first').addClass('fw_active');var $cur=$t.ul.find('li.fw_active a').clone('false').addClass('current').insertBefore($t.ul);if(window.PIE){PIE.attach($cur.get(0));}
$cur.unbind('click').click(function(e){e.preventDefault();if(!$t.hasClass('active_select')){if(jQuery('div.active_select').length)jQuery('div.active_select a.current').click();$t.addClass('active_select').parent().addClass('active_select_parent');$t.ul.stop().fadeIn(200);}else{$t.removeClass('active_select').parent().removeClass('active_select_parent');$t.ul.stop().hide();}});var hddnitem=$t.find('input:hidden');if(hddnitem){var activeA=$t.ul.find('li.fw_active a').first();if(typeof(activeA)!=="undefined"){var data=activeA.attr('href');$t.inp=hddnitem.val(data?data.indexOf("#")==0?data.substring(1):data:"");}
$t.ul.find('a').unbind('click').click(function(e){e.preventDefault();var href=jQuery(this).attr('href');if(typeof href!=='undefined'&&href!=''&&href.substring(0,1)!='#'){document.location=href;}
if(jQuery(this).parent().hasClass('fw_active')){$cur.click();return jQuery(this);}
$t.ul.find('li.fw_active').removeClass('fw_active');jQuery(this).parent().addClass('fw_active');$cur.html(jQuery(this).text()+'<span class="img_txt txt_select_arrow"></span>');if(typeof href!=='undefined'&&href!=''){$t.inp.val(href.substring(1));}
$cur.click();return jQuery(this);});}
$cur.append('<span class="img_txt txt_select_arrow"></span>');});};var MosaikGrid=function(area){this.area=area;this.$listHolder=null;this.$filterPopup=null;this.$actibveFilters=null;this.Filters=null;this.PageNumer=0;this.LanguageNodeId=null;this.SystemLineId=null;this.init=function(){var self=this;this.$listHolder=$('#listHolder');this.$filterPopup=$('#filterPopup');this.$actibveFilters=$('#activeFilters');this.LanguageNodeId=typeof languageNodeId!='undefined'?languageNodeId:0;this.SystemLineId=typeof systemLineId!='undefined'?systemLineId:0;$('#submitFilter').click(function(e){e.preventDefault();self.PageNumer=0;self.Filters=self._getFiltersList();self.loadItems(true,function(){self.setFilters(self.Filters);$.magnificPopup.close()});});$("#js-load-more-button").on('click',function(e){e.preventDefault();self.Filters=self._getFiltersList();projects.loadMoreEvent(self.Filters);});$('#loadMore').click(function(e){e.preventDefault();var $link=$(this);if($link.hasClass('load')){return;}
$link.addClass('load');self.PageNumer++;self.loadItems(false,function(){$link.removeClass('load');});});console.log(1)};this.setFilters=function(array){var self=this;this.$actibveFilters.find('a.remove').click(function(e){e.preventDefault();if($(this).hasClass('load')){return;}
$(this).addClass('load');var id=$(this).data('id');self.clearFilter(id);});};this.clearFilter=function(id){var self=this;this.Filters[id]['value']=0;this.loadItems(true,function(){self.setFilters(self.Filters);self._setFiltersList(self.Filters);});};this.loadItems=function(clear,callback){var self=this;var languageNodeId=this.LanguageNodeId;var systemLineId=this.SystemLineId;var selectFilters=this._getStringOfFilters(this.Filters);var page=this.PageNumer;var action='GetSystems';if(this.area=='system'){action='GetSystems';}
if(this.area=='project'){action='GetProjects';if(projects){projects.loadMoreEvent(this.Filters,callback,1);return true;}}
$.ajax({method:'GET',url:'/Umbraco/Surface/Ajax/'+action+'?languageNodeId='+languageNodeId+'&systemLineId='+systemLineId+''+selectFilters+'&page='+page,success:function(data){data=$.trim(data);self.$listHolder.closest('.section').parent().find("#nodata").remove();if(data.indexOf('id="nodata"')>-1){self.$listHolder.closest('.section').parent().prepend(data);data='';}
self._fillList(data,clear);$('div.mosaik').parent().mosaikRendering();if(data.indexOf('id="lastPage"')!=-1||!data){$('#loadMore').hide();}
else{$('#loadMore').show();}
if(typeof callback=='function'){callback();}},dataType:'html',cache:false});};this._getFiltersList=function(){var obj={};$('input.filter-value',this.$filterPopup).each(function(e,input){var $input=$(input);var name=$input.attr('name');obj[''+name+'']={fid:name};var lival=$input.val();obj[''+name+'']['value']=lival;$input.parent().find("ul li").each(function(lip,liel){var liel$=jQuery(liel);if(liel$.attr("data-id")==lival){obj[''+name+'']['name']=liel$.text();return false;}});});return obj;};this._setFiltersList=function(obj){$('input.filter-value',this.$filterPopup).each(function(e,input){var $input=$(input);var name=$input.attr('name');var lival=obj[''+name+'']['value'];$input.val(lival);var selitem=null;var items=$input.parent().find("ul li");items.each(function(lip,liel){var liel$=jQuery(liel);if(liel$.attr("data-id")==lival){selitem=liel$;}else{liel$.removeClass("fw_active");};});if(!selitem&&items.length>0)selitem=$(items[0]);if(selitem){selitem.find("a").trigger("click");$input.parent().find("a.current span").trigger("click");}});return obj;};this._fillList=function(html,clear){if(clear){this.$listHolder.empty();}
this.$listHolder.append(html);};this._getStringOfFilters=function(obj){var str='';for(var key in obj){str+='&selectFilters['+key+']='+obj[key]['value'];}
return str;};this.init();};var screenSizeCalc=function(){if(!headerH)headerH=$('#header').height();if($('#big_slider').length){var w=$('#page').width()<1500?$('#page').width():1500;$('#big_slider .item').width(w);var cur=$('#big_slider').data("scrollable").getIndex();var leftPos=$('#big_slider .items').css('left');cur++;if($('#big_slider .item').length>1){if(leftPos!='0px'){$('#big_slider .items').css('left',0-(cur)*w+'px');}
else{$('#big_slider .items').css('left',-w+'px');}}
var h=$('#big_slider .item img').height();$('#big_slider,#big_slider .item').height(h);}
if($('div.section_systems div.system').length){var h=$(window).height()-headerH;$('div.section_systems div.system').height(h);}
if($('div.mosaik').length){$('div.mosaik').closest('.section').addClass('overflow');var h=Math.ceil($('div.mosaik').closest('.section').width()/2);if($('div.mosaik').closest('.section').width()<=750){h=$('div.mosaik').closest('.section').width();}
if(h%2!=0){h--;}
$('div.mosaik div.block').width(h);$('div.mosaik div.item, div.mosaik_odd div.item:first').height(h/2);$('div.mosaik div.block:first-child div.item:first-child, div.mosaik_odd div.item_vertical, div.mosaik div.item_big').height(h);}};function getScreen(url,size){if(url===null)return"";size=(size===null)?"big":size;var vid,results;results=url.match("[\\?&]v=([^&#]*)");vid=(results===null)?null:results[1];if(vid==null){results=url.match(".*embed\/([^\?&#/]+).*");vid=(results===null)?url:results[1];}
if(size=="small"){return"https://img.youtube.com/vi/"+vid+"/2.jpg";}else{return"https://img.youtube.com/vi/"+vid+"/0.jpg";}}
function setItemDataUrl(){var items=$('.short_item_list .item');items.each(function(){var item=$(this);var link=item.data('url');if(link!=''){var links=item.find('a');links.each(function(){$(this).attr('href',link);});}});}
function clearBasket(){var total_node=$('.cart-trigger .total');var success_node=$('#standard .success');if(total_node&&success_node){total_node.text('0');}}
function FW_formCallbackError(data){$('html, body').animate({scrollTop:($(".fw_form_feedback_error").offset().top-100)},600);}
function FW_formCallbackSuccess(data){$('html, body').animate({scrollTop:($(".fw_form_feedback_success").offset().top-100)},600);}
function removeRegistrationText(){var body=$('body');if(body.hasClass('page-2')){if($('.fw_form_feedback_success > .black_text').length>0){$("#standard .content-style p").remove();}}}
jQuery.fn.headerShadow=function(){return $(this).each(function(){var $t=$(this);checkOffset();$(window).on('resize',checkOffset);$(window).on('scroll',checkOffset);function checkOffset(){var $offset=5;if($(window).scrollTop()>$offset){$t.addClass('shadow');}else{$t.filter('.shadow').removeClass('shadow');}}});}
jQuery.fn.optionSearch=function(){return $(this).each(function(){var $t=$(this);$t.list=$t.find('ul');$t.links=$t.list.find('a');$(document).on('keyup',function(e){var $letter=keyboardMap[e.keyCode];if($t.list.is(':visible')){$t.links.each(function(){if($(this).text().charAt(0).toUpperCase()==$letter){$t.list.scrollTop(0);$t.list.scrollTop($(this).offset().top-$t.list.offset().top)
return false;}});}});var keyboardMap=["","","","CANCEL","","","HELP","","BACK_SPACE","TAB","","","CLEAR","ENTER","ENTER_SPECIAL","","SHIFT","CONTROL","ALT","PAUSE","CAPS_LOCK","KANA","EISU","JUNJA","FINAL","HANJA","","ESCAPE","CONVERT","NONCONVERT","ACCEPT","MODECHANGE","SPACE","PAGE_UP","PAGE_DOWN","END","HOME","LEFT","UP","RIGHT","DOWN","SELECT","PRINT","EXECUTE","PRINTSCREEN","INSERT","DELETE","","0","1","2","3","4","5","6","7","8","9","COLON","SEMICOLON","LESS_THAN","EQUALS","GREATER_THAN","QUESTION_MARK","AT","A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z","OS_KEY","","CONTEXT_MENU","","SLEEP","NUMPAD0","NUMPAD1","NUMPAD2","NUMPAD3","NUMPAD4","NUMPAD5","NUMPAD6","NUMPAD7","NUMPAD8","NUMPAD9","MULTIPLY","ADD","SEPARATOR","SUBTRACT","DECIMAL","DIVIDE","F1","F2","F3","F4","F5","F6","F7","F8","F9","F10","F11","F12","F13","F14","F15","F16","F17","F18","F19","F20","F21","F22","F23","F24","","","","","","","","","NUM_LOCK","SCROLL_LOCK","WIN_OEM_FJ_JISHO","WIN_OEM_FJ_MASSHOU","WIN_OEM_FJ_TOUROKU","WIN_OEM_FJ_LOYA","WIN_OEM_FJ_ROYA","","","","","","","","","","CIRCUMFLEX","EXCLAMATION","DOUBLE_QUOTE","HASH","DOLLAR","PERCENT","AMPERSAND","UNDERSCORE","OPEN_PAREN","CLOSE_PAREN","ASTERISK","PLUS","PIPE","HYPHEN_MINUS","OPEN_CURLY_BRACKET","CLOSE_CURLY_BRACKET","TILDE","","","","","VOLUME_MUTE","VOLUME_DOWN","VOLUME_UP","","","SEMICOLON","EQUALS","COMMA","MINUS","PERIOD","SLASH","BACK_QUOTE","","","","","","","","","","","","","","","","","","","","","","","","","","","OPEN_BRACKET","BACK_SLASH","CLOSE_BRACKET","QUOTE","","META","ALTGR","","WIN_ICO_HELP","WIN_ICO_00","","WIN_ICO_CLEAR","","","WIN_OEM_RESET","WIN_OEM_JUMP","WIN_OEM_PA1","WIN_OEM_PA2","WIN_OEM_PA3","WIN_OEM_WSCTRL","WIN_OEM_CUSEL","WIN_OEM_ATTN","WIN_OEM_FINISH","WIN_OEM_COPY","WIN_OEM_AUTO","WIN_OEM_ENLW","WIN_OEM_BACKTAB","ATTN","CRSEL","EXSEL","EREOF","PLAY","ZOOM","","PA1","WIN_OEM_CLEAR",""];});}
function checkVideoService(url){url.match(/(http:|https:|)\/\/(player.|www.)?(vimeo\.com|youtu(be\.com|\.be|be\.googleapis\.com))\/(video\/|embed\/|watch\?v=|v\/)?([A-Za-z0-9._%-]*)(\&\S+)?/);if(RegExp.$3.indexOf('youtu')>-1){var type='youtube';}else if(RegExp.$3.indexOf('vimeo')>-1){var type='vimeo';if(RegExp.$6=='external'){return{type:'mp4',id:url};}}else if(url.slice(-4)=='.mp4'){return{type:'mp4',id:url};}
return{type:type,id:RegExp.$6};}
jQuery.fn.setVideoBackground=function(){return $(this).each(function(){var $t=$(this);$t.video=$t.find('iframe');if($t.video.length){$t.videoFrame=$t.find('iframe')[0];$t.service=checkVideoService($t.videoFrame.src);$t.data('aspectRatio',$t.videoFrame.width/$t.videoFrame.height);if($t.service.type=='youtube'){}else if($t.service.type=='vimeo'){}}
function setHeight(){$t.css('height',$(window).height()-$('#header').outerHeight());if($t.video.length){setAspectRatio($t);}};});}
var YT_Videos=[],YT_Players=[];function setYoutubeVideo(){var is_background,player_controls;if(!$('.js_youtube_video').length){return false;}
var tag=document.createElement('script');tag.src="https://www.youtube.com/iframe_api";var firstScriptTag=document.getElementsByTagName('script')[0];firstScriptTag.parentNode.insertBefore(tag,firstScriptTag);$('.js_youtube_video').each(function(i){is_background=false;player_controls=0;$(this).attr({'id':'player-youtube-'+i,'data-id':i});if($(this).closest('.js_video_bg').length){is_background=true;}
if($(this).data('controls')){player_controls=1;}
var el=$({'player_id':'player-youtube-'+i,'video_id':checkVideoService($(this).find('iframe')[0].src).id,'is_background':is_background,'player_controls':player_controls});console.log(el)
YT_Videos.push(el);});}
function create_ytplayer(){for(i in YT_Videos){YT_Players[i]=new YT.Player(YT_Videos[i][0].player_id,{playerVars:{'autoplay':0,'controls':YT_Videos[i][0].player_controls,'autohide':1,'wmode':'opaque','showinfo':0,'loop':1,'mute':0,'rel':0,'playlist':YT_Videos[i][0].video_id},videoId:YT_Videos[i][0].video_id,events:{onReady:onPlayerReady,onStateChange:onPlayerStateChange}});}}
if(typeof YT=='object'){create_ytplayer();}
function onYouTubeIframeAPIReady(){create_ytplayer();}
function onPlayerReady(e){if($(e.target.a).closest('.js_video_bg').length){e.target.setVolume(0),e.target.mute(),e.target.playVideo();}}
function onPlayerStateChange(e){console.log(e)
if(1==e.data){$(e.target.f).addClass('active');}
if($(e.target.f).closest('.js_player').length){$(e.target.f).closest('.js_player').addClass('active');}}
function setAspectRatio(el){var w=el.width()+100,h=el.height()+100,video=el.find('iframe'),aspectRatio=el.data('aspectRatio');if(video.data('id')!=undefined){if(YT_Players[video.data('id')]){}
if(w/h>aspectRatio){video.css({width:w,height:h*aspectRatio})}else if(w/h>1){video.css({width:w*aspectRatio,height:h})}else{video.css({width:(w+100)*aspectRatio,height:h})}}};